import restalker
import sys

if len(sys.argv) > 1:
    with open(sys.argv[1]) as f:
        target = f.read()
else:
    target = """'
logo
Wallet
Intercambiar
Explorador
Comprar Bitcoin
Operación

Explorador
Bitcoin Explorer
Dirección
USD
Buscar tu transacción, una dirección o un bloque
Dirección
USD
BTC
Esta dirección tiene tiempos 1,795 transaccionados en la cadena Bitcoin. Ha recibido un total de 29,679.60047496 BTC (1.620.083.548,42 US$) y ha enviado un total de 29,679.34007776 BTC (1.620.069.334,44 US$). El valor actual de esta dirección es 0.26039720 BTC (14.213,98 US$).
Dirección
1F1tAaz5x1HUXrCNLbtMDqcw6o5GNn4xqX
Formato
BASE58 (P2PKH)
Transacciones
1795
Total recibido
29679.60047496 BTC
Total enviado
29679.34007776 BTC
Saldo final
0.26039720 BTC
Transacciones
Cuota
0.00037168 BTC
(99.380 sat/B - 24.845 sat/WU - 374 bytes)
+0.00100000 BTC
Hash
934f21df66c99694815c8ca2273b984a74d84efa16e17b081d66e2a645cab119
2021-10-11 16:03
1PYzcz53HxXCFMKygNAsSdHXuhCx6ec2Y5
0.00100000 BTC
1PYzcz53HxXCFMKygNAsSdHXuhCx6ec2Y5
0.05530390 BTC
1F1tAaz5x1HUXrCNLbtMDqcw6o5GNn4xqX
0.00100000 BTC
1PYzcz53HxXCFMKygNAsSdHXuhCx6ec2Y5
0.05493222 BTC
Cuota
0.00005184 BTC
(27.141 sat/B - 6.785 sat/WU - 191 bytes)
+0.00383816 BTC
Hash
126527242ebfaec6f39d93585a31ca61ac859bf81d093b798b12569bba7d2bfe
2021-09-11 00:45
129NVRj7RxBpZsSzbmhAgsZZ1AidWuF828
0.00389000 BTC
1F1tAaz5x1HUXrCNLbtMDqcw6o5GNn4xqX
0.00383816 BTC
Cuota
0.00000516 BTC
(2.314 sat/B - 0.578 sat/WU - 223 bytes)
+0.00000684 BTC
Hash
0987dda228544ab534caca9ea748a66f0ce65a3ceb881d132a1fdfcce479e51b
2021-08-24 13:04
1BcsJid3oVmBSVF4tdQJEEHfkcnFLj6fjv
0.00340200 BTC
1F1tAaz5x1HUXrCNLbtMDqcw6o5GNn4xqX
0.00000684 BTC
bc1qn8rsv3gw82ldyx2y7w5crf7mxkv6kt7eg3rzeq
0.00339000 BTC
Cuota
0.00037571 BTC
(1.022 sat/B - 0.256 sat/WU - 36772 bytes)
(1.024 sat/vByte - 36691 virtual bytes)
+0.00001061 BTC
Hash
58c3367d784ef5e552cf917ea2cdf32ce0fee7522b601fdc93fd526617e6420f
2021-08-11 21:40
bc1qmyhkstfk5trd0eycpvu548wtsw70sj4rdnlx5w
0.14064664 BTC
1PAiCX635zxNZNSkeKeqH6W85AZHBLWGAY
0.00008927 BTC
35C9Ly4pBDBL6SVkyFtKbSwWbKYX16yHih
0.00003000 BTC
1A8D3FGVHqdGYnUnRchZtah6HuepcYespQ
0.00001800 BTC
bc1q5chpw8560qvkn6z4wnlgvqw5u85lcutvdsua6y
0.00001217 BTC
33cn2pd6DTf56XBiacChiCk5nyC5HU9w65
0.00001254 BTC
1KgPZAd98yRAgZwjn55BsS9pGbUFKj8ziX
0.00001157 BTC
3CZAwnU59Ts32JJcMF1pJf3ew43j5jEuTS
0.00001000 BTC
1FXmZevQcV15EDbjXwGh5Qf2yBiSFJg974
0.00001729 BTC
bc1q7ssrlr0my89mytwesrqltv273laxyrnmlhy79j
0.00001000 BTC
3819qnmziQ6fBPDca6sPW2C32Em6FCjg8w
0.00005000 BTC
Cargar más gastos... (1113 restantes)
Cuota
0.00001361 BTC
(6.049 sat/B - 2.375 sat/WU - 225 bytes)
(9.451 sat/vByte - 144 virtual bytes)
+0.00309719 BTC
Hash
20b49f1dd0945575305ab64cb92c4cc1c6361e48426d459f58d82c1ea0c695e9
2021-08-10 20:13
bc1qvxx902lv2vcgvw3k0h4487cekrvgzfc6cxtenq
0.33000966 BTC
1F1tAaz5x1HUXrCNLbtMDqcw6o5GNn4xqX
0.00309719 BTC
bc1qdehkush6s5y553hxlrgd3ly6ufh89nm89x4l56
bc1qxhkush6s5y553hxlrgd3ly6ufh89nm89x4l56
bc1p8denc9m4sqe9hluasrvxkkdqgkydrk5ctxre5nkk4qwdvefn0sdsc6eqxe
bc1pxdenc9m4sqe9hluasrvxkkdqgkydrk5ctxre5nkk4qwdvefn0sdsc6eqxe
0.32689886 BTC
1
2
3
4
5
+10
0x12ae66cdc592e10b60f9097a7b0d3c59fce29876
0x12AE66CDc592e10B60f9097a7b0D3C59fce29876
0x111111111111111111111aaaaaaaaaaaaaaaaaaa
0x111111111111111111111AAAAAAAAAAAAAAAAAAA
0x1111111111xxxxxxxxxxxxxxAAAAAAAAAAAAAAAA
4473m2PotByhryknyafx5FPbojXqoQRS5BciBvw78jkffWTtgzynQqNZRY5XyxgbimJotUSkwYGZ9f2aYjZYXvvbVoeG3Ft
4HMcpBpe4ddJEEnFKUJHAYhGxkeTRH82sf36giEp9AcNfDBfkAtRLX7A6rZz18bbNHPNV7ex6WYbMN3aKisFRJZ8M7yKhzQhKW3ECCLWQw
84LooD7i35SFppgf4tQ453Vi3q5WexSUXaVgut69ro8MFnmHwuezAArEZTZyLr9fS6QotjqkSAxSF6d1aDgsPoX849izJ7m
47ewoP19TN7JCEnFKUJHAYhGxkeTRH82sf36giEp9AcNfDBfkAtRLX7A6rZz18bbNHPNV7ex6WYbMN3aKisFRJZ8Ebsmgef
4HMcpBpe4ddJEEnFKUJHAYhGxkyTRH82sf36giEp9AcNfDBfkAtRLX7A6rZz18bbNHPNV7ex6WYbMN3aKisFRJZ8M7yKhzQhKW3ECCLWQw
84LooD7i35SFppgf4tQ453Vi3q5WexXXXXXXXXX9ro8MFnmHwuezAArEZTZyLr9fS6QotjqkSAxSF6d1aDgsPoX849izJ7m
5473m2PotByhryknyafx5FPbojXqoQRS5BciBvw78jkffWTtgzynQqNZRY5XyxgbimJotUSkwYGZ9f2aYjZYXvvbVoeG3Ft
t1RytpPXoGvevVECv5NsRVD2BTrz78xeiDQ
t1KLGj3izuKveu1eFZUiwp3BEKHQAiYv2Z7
t1KLGjXXXXXXXXXXXXXiwp3BEKHQAiYv2Z7
t1b2ArRwLq6KbdJFzJVYPxgUVT1d9QuBzTf
t3Vz22vK5z2LcKEdg16Yv4FFneEL1zg9ojd
zs1wkejr23wqa9ptpvv73ch3wr96lh8gnyx3689skmyttljy4nyfj69eyclukwkxrhr3rrkgxvnur0
zs1wkejr23wqa9ptpvv73ch3wr96lh8gnyx3689skmytXXXXXXXXXXXXyclukwkxrhr3rrkgxvnur0
zcU1Cd6zYyZCd2VJF8yKgmzjxdiiU1rgTTjEwoN1CGUWCziPkUTXUjXmX7TMqdMNsTfuiGN1jQoVN4kGxUR4sAPN4XZ7pxb
zcU1Cd6zYyZCd2VJF8yKgmzjxdiiU1rgTTjEwoN1CGUWCziPkUTXUjXmX7TMqdMNsTfuiGN1jQoVN4kGxUR4sAPXXXXXpxb
XkrJp72ViXiw31PaeGdQ4FjgMo9Qn9VHER
XpESxaUmonkq8RaLLp46Brx2K39ggQe226
XpESxaUmonkq8RaLLp46Brx2K39g26
XpESxaUmonkq8XXXXXXXXXXXXXXggQe226
1FRMM8PEiWXYax7rpS6X4XZX1aAAxSWx1CrKTyrVYhV24fg
5CK8D1sKNwF473wbuBP6NuhQfPaWUetNsWUNAAzVwTfxqjfr
CpjsLDC1JFyrhm3ftC9Gs4QoyrkHKhZKtK7YqGTRFtTafgp
J4iggBtsWsb61RemU2TDWDXTNHqHNfBSAkGvVZBtn1AJV1a
J4iggBtsWsb61RXXXXXXXXXXXXXXXXXXAkGvVZBtn1AJV1a
126xi3Tj9HYjXio1k3ae9YLeMPUjrMvznpdtbKZEuiPFoeJt
14EDPoc8SNcALsdn2NzKPazBJ1ExhZmBCx94uiyiaJvtUwCq
HeSXpZGijCJqP7amSPBMAStj98hpXLsoNRwBQtmqkMcRngeD
rA9bXGJcXvZKaWofrRphdJsBWzhyCfH3z
rUqqN1KKvLSknssUXrLX48vtnNdpvaqsZ7
rUqqN1XXXXxxxxxUXrLX48vtnNdpvaqsZ7
XV5sbjUmgPpvXv4ixFWZ5ptAYZ6PD2q1qM6owqNbug8W6KV
XV5sbjUmgPpvXv4ixFWZ5ptAYZ6PD2gYsjNFQLKYW33DzBm
XV5sbjUmgPpvXv4ixFWZ5ptAYZ6PD2m4Er6SnvjVLpMWPjR
XV5sbjUmgPpvXv4ixFWZ5ptAYZ6PD2m4Er6XXXxxxXMWPjR
bnb1qx8u39hqcykjy5puv582gvqy5520dsz7fdh9ak
bnb10af52w77pkehgxhnwgeca50q2t2354q4xamz5y
bnb1cyhhgx4mw4gts2h4f2ju4e2lcr3rq4mjp4rtky
bnb1cyhhgx4mw4gts2XXXXXXXe2lcr3rq4mjp4rtky

localhost:43110/1MaiL5gfBM1cyb4a8e3iiL8L5gXmoAJu27
1MaiL5gfBMxxxx8e3iiL8L5gXmoAxxJu27
mail.zeronetwork.bit

Comprar criptomonedas
Ya lo has pensado, es hora de actuar.
Crear un Wallet. Registrarse en Exchange. Comprar Bitcoin en minutos.
Empezar


Twitter

Instagram

Medio
Productos
Wallet
Intercambiar
Aprenda
Explorador
Mercados
Precios
Gráficos
Recursos
API
Estado
Código abierto
Investigación
Privacidad
Wallet Support
Exchange Support
Blog
Acerca de
Equipo
CarrerasCONTRATACIONES
Prensa
Prime
Ventures
Institucional

Español

Blockchain
NMLS ID: 2024031


1.23.22
Utilizamos cookies para mejorar su experiencia de usuario. Al continuar en nuestro sitio web, usted acepta nuestro política de privacidad.
Aceptar
# FROM https://github.com/k-vitali/Malware-Misc-RE/tree/5a815f44ffb1adfb91fef595b2078514f93aa44a
uuid,event_id,category,type,value,comment,to_ids,date,object_relation,attribute_tag,object_uuid,object_name,object_meta_category
"5d30f6cf-b230-4ee6-8914-57e368f8e8cf",1204,"Internal reference","text","July 15 build

Exports:
ss2
start

Blacklisted Files & Folders:
.dll
.exe
.sys
.mui
.tmp
.lnk
.config
.manifest
.tlb
.olb
.blf
.ico
.regtrans-ms
.devicemetadata-ms
.settingcontent-ms
.bat
.cmd
.ps1
desktop.ini
iconcache.db
ntuser.dat
ntuser.ini
ntuser.dat.log1
ntuser.dat.log2
usrclass.dat
usrclass.dat.log1
usrclass.dat.log2
bootmgr
bootnxt
temp\
.+\\Microsoft\\(User Account Pictures|Windows\\(Explorer|Caches)|Device Stage\\Device|Windows)\\

Service & Process Kill (taskkill, net.exe & sc config "" start=disabled):
ccflic0.exe
ccflic4.exe
healthservice.exe
ilicensesvc.exe
nimbus.exe
prlicensemgr.exe
certificateprovider.exe
proficypublisherservice.exe
proficysts.exe
erlsrv.exe
vmtoolsd.exe
managementagenthost.exe
vgauthservice.exe
epmd.exe
hasplmv.exe
spooler.exe
hdb.exe
ntservices.exe
n.exe
monitoringhost.exe
win32sysinfo.exe
inet_gethost.exe
taskhostw.exe
proficy administrator.exe
ntevl.exe
prproficymgr.exe
prrds.exe
prrouter.exe
prconfigmgr.exe
prgateway.exe
premailengine.exe
pralarmmgr.exe
prftpengine.exe
prcalculationmgr.exe
prprintserver.exe
prdatabasemgr.exe
preventmgr.exe
prreader.exe
prwriter.exe
prsummarymgr.exe
prstubber.exe
prschedulemgr.exe
cdm.exe
musnotificationux.exe
npmdagent.exe
client64.exe
keysvc.exe
server_eventlog.exe
proficyserver.exe
server_runtime.exe
config_api_service.exe
fnplicensingservice.exe
workflowresttest.exe
proficyclient.exe
vmacthlp.exe
msdtssrvr.exe
sqlservr.exe
msmdsrv.exe
reportingservicesservice.exe
dsmcsvc.exe
winvnc4.exe
client.exe
collwrap.exe
bluestripecollector.exe
sqlbrowser.exe
dsmcad.exe
nimcluster.exe
googleupdate.exe
smc.exe
bcrservice.exe
dbsrv9.exe
rtvscan.exe
bcreporter.exe
csadmin.exe
csdbsync.exe
csmon.exe
csauth.exe
cslog.exe
csradius.exe
cstacacs.exe
url_response.exe
vmware-converter-a.exe
vmware-converter.exe
avagent.exe
paxton.net2.clientservice.exe
paxton.net2.commsserverservice.exe
avscc.exe
prunsrv.exe
googlecrashhandler.exe
googlecrashhandler64.exe
vmwaretray.exe
nd2svc.exe
tnslsnr.exe
omtsreco.exe
oracle.exe
patrolagent.exe
scfagent_64.exe
patrolperf.exe
rscdsvc.exe
rscd.exe
pmgreader.exe
firefox.exe
chrome.exe
netsession_win.exe
pcsws.exe
pcscm.exe
cwbunnav.exe
rdrcef.exe
ndrvx.exe
ndrvs.exe
dr_serviceengine.exe
teamviewer_service.exe
sqlagent.exe
dwrcst.exe
ccm messaging.exe
zoolz.exe
agntsvc.exe
dbeng50.exe
dbsnmp.exe
encsvc.exe
excel.exe
firefoxconfig.exe
infopath.exe
isqlplussvc.exe
msaccess.exe
msftesql.exe
mspub.exe
mydesktopqos.exe
mydesktopservice.exe
mysqld.exe
mysqld-nt.exe
mysqld-opt.exe
ocautoupds.exe
ocomm.exe
ocssd.exe
onenote.exe
outlook.exe
powerpnt.exe
sqbcoreservice.exe
sqlwriter.exe
steam.exe
synctime.exe
tbirdconfig.exe
thebat.exe
thebat64.exe
thunderbird.exe
visio.exe
winword.exe
wordpad.exe
xfssvccon.exe
tmlisten.exe
pccntmon.exe
cntaosmgr.exe
ntrtscan.exe
mbamtray.exe
qhactivedefense.exe
qhwatchdog.exe
qhsafetray.exe
avgsvc.exe
avgui.exe
v3lite.exe
v3main.exe
v3sp.exe
avastui.exe
avastsvc.exe
avguard.exe
avshadow.exe
avgnt.exe
avira.servicehost.exe
avira.systray.exe
bdagent.exe
bdredline.exe
bdss.exe
bullguardbhvscanner.exe
bullguardscanner.exe
bullguardtray.exe
bullguardupdate.exe
bullguard.exe
cmdagent.exe
cistray.exe
cis.exe
spideragent.exe
dwengine.exe
dwarkdaemon.exe
dwnetfilter.exe
a2service.exe
a2guard.exe.a2start.exe
egui.exe
ekrn.exe
fshoster32.exe
fshoster64.exe
fortisslvpndaemon.exe
fortiesnac.exe
fortiwf.exe
fortitray.exe
fchelper64.exe
fortiproxy.exe
fcappdb.exe
fcdblog.exe
avp.exe
avpui.exe
mbamservice.exe
mcsacore.exe
mcapexe.exe
mcshield.exe
mcsvhost.exe
nortonsecurity.exe
psuaservice.exe
psuamain.exe
psanhost.exe
sdrservice.exe
swc_service.exe
swi_service.exe
ssp.exe
ccsvchst.exe
smcgui.exe
coreserviceshell.exe
coreframeworkhost.exe
uiwatchdog.exe
uiseagnt.exe
paamsrv.exe
psh_svc.exe
aupdrun.exe
acaas.exe
acaegmgr.exe
acaif.exe
acais.exe
ahnsd.exe
ahnsdsv.exe
autoup.exe
v3clnsrv.exe
v3medic.exe
v3svc.exe
aflogvw.exe
ahnrpt.exe
atwsctsk.exe
v3exec.exe
v3imscn.exe
monsvcnt.exe
monsysnt.exe
aexnsrcvsvc.exe
aexsvc.exe
atrshost.exe
ctdataload.exe
aexagentuihost.exe
aexnsagent.exe
aclntusr.exe
aexswdusr.exe
pxemtftp.exe
aclient.exe
securitycenter.exe
starta.exe
stopa.exe
anvir.exe
csrss_tc.exe
ashavast.exe
ashbug.exe
ashchest.exe
ashcmd.exe
ashdisp.exe
ashenhcd.exe
ashlogv.exe
ashmaisv.exe
ashpopwz.exe
ashquick.exe
ashserv.exe
ashsimp2.exe
ashsimpl.exe
ashskpcc.exe
ashskpck.exe
ashupd.exe
ashwebsv.exe
aswdisp.exe
aswregsvr.exe
aswserv.exe
aswupdsv.exe
aswwebsv.exe
avengine.exe
afwserv.exe
avastemupdate.exe
unsecapp.exe
avgamsvr.exe
avgas.exe
avgcc32.exe
avgcc.exe
avgctrl.exe
avgdiag.exe
avgemc.exe
avgfws8.exe
avgfwsrv.exe
avginet.exe
avgmsvr.exe
avgrssvc.exe
avgscanx.exe
avgserv9.exe
avgserv.exe
avgupd.exe
avgupdln.exe
avgupsvc.exe
avgvv.exe
avgwb.dat
avgw.exe
avgwizfw.exe
guard.exe
avgcsrvx.exe
avgidsagent.exe
avgidsmonitor.exe
avgidsui.exe
avgidswatcher.exe
avgam.exe
avgnsx.exe
avgfws9.exe
avgrsx.exe
avgtray.exe
avgwdsvc.exe
sidebar.exe
avgchsvx.exe
avgcmgr.exe
avgemcx.exe
avgfws.exe
avgmfapx.exe
avgcefrend.exe
avgcsrva.exe
avgemca.exe
avgnsa.exe
avgrsa.exe
loggingserver.exe
toolbarupdater.exe
wtusystemsuport.exe
avgregcl.exe
avgsystx.exe
vprot.exe
avcenter.exe
avconfig.exe
avesvc.exe
avmailc.exe
avmcdlg.exe
avnotify.exe
avscan.exe
guardgui.exe
avadmin.exe
avfwsvc.exe
avwebgrd.exe
fwinst.exe
sysoptenginesvc.exe
bavtray.exe
bhipssvc.exe
bmrt.exe
seccenter.exe
gziface.exe
gzserv.exe
bdc.exe
bdlite.exe
bdmcon.exe
bdsubmit.exe
deloeminfs.exe
livesrv.exe
setloadorder.exe
vsserv.exe
xcommsvr.exe
bka.exe
bkavsystemserver.exe
blupro.exe
blackd.exe
blackice.exe
proutil.exe
rapapp.exe
basfipm.exe
isafe.exe
cavrid.exe
vetmsg.exe
amswmagt
caf.exe
capmuam
agt.exe
ccnfagent.exe
ccsmagtd.exe
cfftplugin.exe
cfnotsrvd.exe
cfsmsmd.exe
alert.exe
igateway.exe
inotask.exe
caantispyware.exe
caavcmdscan.exe
caav.exe
caavguiscan.exe
cafw.exe
calogdump.exe
capfaem.exe
capfsem.exe
cappactiveprotection.exe
casecuritycenter.exe
caunst.exe
cavrep.exe
cctray.exe
ccupdate.exe
isafinst.exe
itmrt_supportdiagnostics.exe
itmrtsvc.exe
itmrt_trace.exe
ppclean.exe
umxagent.exe
umxcfg.exe
umxfwhlp.exe
umxpol.exe
unvet32.exe
capfasem.exe
ccprovsp.exe
ppctlpriv.exe
casc.exe
ccschedulersvc.exe
ccsystemreport.exe
inonmsrv.exe
inoweb.exe
auth8021x.exe
krbcc32s.exe
pep.exe
realmon.exe
repmgr64.exe
csacontrol.exe
leventmgr.exe
okclient.exe
clamscan.exe
clamtray.exe
clamwin.exe
ccemflsv.exe
cssauth.exe
cavscan.exe
clps.exe
clpsla.exe
clpsls.exe
cmdinstall.exe
cfpconfig.exe
cfp.exe
cfplogvw.exe
cfpsbmit.exe
cfpupdat.exe
crashrep.exe
cpf.exe
cfpconfg.exe
csfalconservice.exe
cylanceui.exe
cylancesvc.exe
cramtray.exe
crssvc.exe
amsvc.exe
frzstate2k.exe
drwagnui.exe
drweb32.exe
drweb32w.exe
drweb386.exe
drwebcgp.exe
drwebdc.exe
drweb.exe
drwebmng.exe
drwebscd.exe
drwebupw.exe
drwebwcl.exe
drwebwin.exe
drwinst.exe
spiderml.exe
spidernt.exe
spiderui.exe
drwagntd.exe
drwupgrade.exe
drwebcom.exe
eeyeevnt.exe
retinaengine.exe
a2guard.exe
a2start.exe
administrator.exe
control_panel.exe
usergate.exe
esmagent.exe
era.exe
ppmcativedetection.exe
vettray.exe
cavtray.exe
inorpc.exe
inort.exe
ca.exe
caissdt.exe
etagent.exe
etloganalyzer.exe
etrssfeeds.exe
evtarmgr.exe
evtmgr.exe
etreporter.exe
etconsole3.exe
etwcontrolpanel.exe
useranalysis.exe
etcorrel.exe
evtprocessecfile.exe
etscheduler.exe
useractivity.exe
traptrackermgr.exe
ewidoctrl.exe
ewidoguard.exe
nslocollectorservice.exe
fmon.exe
fortifw.exe
update_task.exe
fpavserver.exe
fprottray.exe
fameh32.exe
fspex.exe
fsaa.exe
bwgo0000
fch32.exe
fih32.exe
fsaua.exe
fsav32.exe
fscuif.exe
fsdfwd.exe
fsgk32.exe
fsgk32st.exe
fsguidll.exe
fsguiexe.exe
fshdll32.exe
fsm32.exe
fsma32.exe
fsmb32.exe
fsorsp.exe
fspc.exe
fsqh.exe
fssm32.exe
setupguimngr.exe
tnbutil.exe
fsavgui.exe
gdscan.exe
avkproxy.exe
avkservice.exe
avktray.exe
avkwctl.exe
gdfirewalltray.exe
gdfwsvc.exe
endpointsecurity.exe
esecservice.exe
gfireporterservice.exe
esecagntservice.exe
rcsvcmon.exe
dolphincharge.e
dolphincharge.exe
loggetor.exe
netalertclient.exe
printdevice.exe
pwdfilthelp.exe
pthosttr.exe
hpqwmiex.exe
ntcaagent.exe
ntcadaemon.exe
ntcaservice.exe
privacyiconclient.exe
rapuisvc.exe
vpatch.exe
tclproc.exe
isscsf.exe
issdaemon.exe
kvdetech.exe
kvmonxp_2.kxp
kvmonxp.kxp
kvolself.exe
kvsrvxp_1.exe
kvsrvxp.exe
kvxp.kxp
ppppwallrun.exe
avpcc.exe
avpexec.exe
avpm.exe
avpncc.exe
avps.exe
avpupd.exe
kav.exe
kavisarv.exe
kavmm.exe
kavss.exe
kavsvc.exe
kis.exe
klnagent.exe
klswd.exe
klwtblfs.exe
kwsprod.exe
up2date.exe
klserver.exe
oespamtest.exe
kavadapterexe.exe
kavlotsingleton.exe
kavfsgt.exe
kavfsrcn.exe
kavfs.exe
kavfswp.exe
kavshell.exe
klnacserver.exe
avpdtagt.exe
netcfg.exe
kavfsscs.exe
kavtray.exe
persfw.exe
avserver.exe
winroute.exe
wrctrl.exe
kabackreport.exe
kaccore.exe
kanmcmain.exe
kastray.exe
kislive.exe
kmailmon.exe
knupdatemain.exe
kswebshield.exe
kxeserv.exe
uplive.exe
kansgui.exe
kansvr.exe
kavstart.exe
kpfwsvc.exe
kwatch.exe
kav32.exe
kissvc.exe
kpfw32.exe
system.exe
wssfcmai.exe
aawservice.exe
ad-aware2007.exe
nlsvc.exe
engineserver.exe
eventparser.exe
log_qtine.exe
mfeann.exe
nailgpip.exe
rpcserv.exe
srvmon.exe
mcagent.exe
mfemactl.exe
macmnsvc.exe
masvc.exe
masalert.exe
msssrv.exe
massrv.exe
msscli.exe
mcshld9x.exe
mgavrtcl.exe
mcappins.exe
mfecanary.exe
macompatsvc.exe
mcvsrte.exe
mfefire.exe
dao_log.exe
firesvc.exe
firetray.exe
mfeesp.exe
naprdmgr.exe
cpd.exe
mfefw.exe
frameworkservic
cmgrdian.exe
mcshell.exe
mfehcs.exe
mcinfo.exe
hwapi.exe
mcafeedatabackup.exe
mcmscsvc.exe
mcnasvc.exe
mcods.exe
mcpromgr.exe
mcproxy.exe
mcuimgr.exe
mpfsrv.exe
mpsevh.exe
mps.exe
msksrver.exe
redirsvc.exe
saservice.exe
siteadv.exe
mfemms.exe
neotrace.exe
vshwin32.exe
mpfagent.exe
mpfconsole.exe
mpf.exe
mpfservice.exe
mpftray.exe
mscifapp.exe
mfevtps.exe
qclean.exe
mcregwiz.exe
rssensor.exe
safeservice.exe
ncdaemon.exe
mcdash.exe
mcdetect.exe
ssscheduler.exe
sahookmain.exe
mskdetct.exe
msksrvr.exe
mskagent.exe
stinger.exe
mcsysmon.exe
mctskshd.exe
mfetp.exe
myagttry.exe
mcupdmgr.exe
rulaunch.exe
mcvsshld.exe
tbmon.exe
alogserv.exe
mcmnhdlr.exe
mghtml.exe
edisk.exe
scan32.exe
frameworkservice.exe
mcconsol.exe
mcscript_inuse.exe
mctray.exe
mcupdate.exe
shstat.exe
udaterui.exe
updaterui.exe
mcepoc.exe
mcepocfg.exe
mcpalmcfg.exe
mcwcecfg.exe
mcwce.exe
frameworkservic.exe
vsmain.exe
oasclnt.exe
vsstat.exe
mcvsftsn.exe
avconsol.exe
avsynmgr.exe
vstskmgr.exe
webscanx.exe
mfewc.exe
mfewch.exe
giantantispywaremain.exe
giantantispywareupdater.exe
gcasservalert.exe
gcascleaner.exe
gcasinstallhelper.exe
gcasnotice.exe
gcasdtserv.exe
gcasserv.exe
gcasswupdater.exe
fcsms.exe
fcssas.exe
nissrv.exe
dpmra.exe
msseces.exe
wscntfy.exe
securitymanager.exe
aesecurityservice.exe
deteqt.agent.exe
omniagent.exe
nerosvc.exe
seanalyzertool.exe
spyemergency.exe
spyemergencysrv.exe
nlclient.exe
crdm.exe
nmagent.exe
ehttpsrv.exe
nod32.exe
nod32krn.exe
nod32kui.exe
nod32view.exe
cclaw.exe
elogsvc.exe
nip.exe
nipsvc.exe
njeeves.exe
npfmsg2.exe
npfmsg.exe
npfsvice.exe
nrmenctb.exe
nvcoas.exe
nvcsched.exe
nymse.exe
zanda.exe
zlh.exe
ixaptsvc.exe
ixavsvc.exe
ixfwsvc.exe
emlproui.exe
emlproxy.exe
mpsvc.exe
onlinent.exe
onlnsvc.exe
scanmsg.exe
scanwscs.exe
tsansrf.exe
tsatisy.exe
tscutynt.exe
tsmpnt.exe
upschd.exe
xfilter.exe
aps.exe
aus.exe
outpost.exe
adminserver.exe
avtask.exe
clshield.exe
console.exe
cpntsrv.exe
padfsvr.exe
pasystemtray.exe
pavfnsvr.exe
pavkre.exe
pavprot.exe
pavreport.exe
pnmsrv.exe
psimsvc.exe
pavupg.exe
remupd.exe
iface.exe
pavfires.exe
pavmail.exe
pavprsrv.exe
pavsched.exe
pavsrv50.exe
pavsrv51.exe
pavsrv52.exe
prevsrv.exe
tpsrv.exe
pagent.exe
pagentwd.exe
psctris.exe
apvxdwin.exe
inicio.exe
pavbckpt.exe
pavjobs.exe
psctrls.exe
pshost.exe
psimreal.exe
pskmssvc.exe
srvload.exe
webproxy.exe
avltmain.exe
firewallgui.exe
pviewer.exe
pview.exe
pmon.exe
qoeloader.exe
fws.exe
ccenter.exe
ravxp.exe
rfwproxy.exe
rfwstub.exe
knownsvr.exe
ras.exe
rasupd.exe
upfile.exe
rstray.exe
ravalert.exe
rav.exe
ravmond.exe
ravmon.exe
ravservice.exe
ravstub.exe
ravtask.exe
ravtray.exe
ravupdate.exe
rnreport.exe
rsnetsvr.exe
scanfrm.exe
rfwmain.exe
rfwsrv.exe
winlog.exe
omslogmanager.exe
snhwsrv.exe
snicheckadm.exe
snichecksrv.exe
snicon.exe
snsrv.exe
smsx.exe
svcharge.exe
svdealer.exe
svframe.exe
svtray.exe
sschk.exe
trjscan.exe
trupd.exe
ssecuritymanager.exe
dltray.exe
dlservice.exe
almon.exe
lmon.exe
savadminservice.exe
savservice.exe
sweepsrv.sys
swnetsup.exe
alsvc.exe
alupdate.exe
savmain.exe
sav32cli.exe
certificationmanagerservicent.exe
emlibupdateagentnt.exe
managementagentnt.exe
mgntsvc.exe
routernt.exe
schdsrvc.exe
scfmanager.exe
scfservice.exe
scftray.exe
op_viewer.exe
sgbhp.exe
pctsauxs.exe
pctsgui.exe
pctssvc.exe
pctstray.exe
regmech.exe
sdtrayapp.exe
svcntaux.exe
swdsvc.exe
swnxt.exe
execstat.exe
seestat.exe
swserver.exe
slee81.exe
kpf4gui.exe
kpf4ss.exe
wrspysetup.exe
acctmgr.exe
alertsvc.exe
alunotify.exe
aluschedulersvc.exe
appsvc32.exe
ccap.exe
ccapp.exe
ccevtmgr.exe
ccproxy.exe
ccpxysvc.exe
ccsetmgr.exe
checkup.exe
cka.exe
comhost.exe
cpdclnt.exe
csinject.exe
csinsm32.exe
csinsmnt.exe
dbserv.exe
defwatch.exe
defwatch
diskmon.exe
djsnetcn.exe
doscan.exe
dwhwizrd.exe
fwcfg.exe
ghost_2.exe
ghosttray.exe
icepack.exe
idsinst.exe
ispwdsvc.exe
issvc.exe
isuac.exe
luall.exe
lucallbackproxy.exe
lucoms~1.exe
lucoms.exe
mcui32.exe
navapsvc.exe
navapw32.exe
navectrl.exe
navelog.exe
navesp.exe
navshcom.exe
navw32.exe
navwnt.exe
ndetect.exe
ngctw32.exe
ngserver.exe
nisoptui.exe
nisserv.exe
nisum.exe
nmain.exe
npfmntor.exe
nprotect.exe
npscheck.exe
npssvc.exe
nscsrvce.exe
nsctop.exe
nsmdtr.exe
olfsnt40.exe
opscan.exe
poproxy.exe
pqibrowser.exe
pqv2isvc.exe
pxeservice.exe
qdcsfs.exe
qserver.exe
reportersvc.exe
rnav.exe
savfmsesp.exe
savroam.exe
savscan.exe
savui.exe
sbserv.exe
scan
explicit.exe
semsvc.exe
sesclu.exe
sevinst.exe
smsectrl.exe
smselog.exe
smsesjm.exe
smsesp.exe
smsesrv.exe
smsetask.exe
smseui.exe
sms.exe
sndmon.exe
sndsrvc.exe
spbbcsvc.exe
symlcsvc.exe
symproxysvc.exe
symsport.exe
symtray.exe
symwsc.exe
sysdoc32.exe
ucservice.exe
updtnv28.exe
urllstck.exe
usrprmpt.exe
v2iconsole.exe
vpc32.exe
vpdn_lu.exe
vprosvc.exe
wfxctl32.exe
wfxmod32.exe
wfxsnt40.exe
lucomserver.exe
savfmselog.exe
savfmsesjm.exe
savfmsectrl.exe
savfmsespamstatsmanager.exe
savfmsesrv.exe
savfmsetask.exe
savfmseui.exe
snac.exe
ssm.exe
reportsvc.exe
vptray.exe
procexp.exe
tdimon.exe
tfun.exe
tfgui.exe
tfservice.exe
tftray.exe
tiaspn~1.exe
traflnsp.exe
asupport.exe
isntsmtp.exe
nsmdemf.exe
nsmdmon.exe
nsmdreal.exe
nsmdsch.exe
ofcdog.exe
pccnt.exe
pccntupd.exe
pcctlcom.exe
pcscnsrv.exe
schupd.exe
tmntsrv.exe
tmpfw.exe
tmproxy.exe
tmas.exe
entitymain.exe
aphost.exe
lwdmserver.exe
mrf.exe
isntsysmonitor
ofcpfwsvc.exe
dwwin.exe
patch.exe
pccclient.exe
pccguide.exe
pcclient.exe
pccpfw.exe
pcscan.exe
pntiomon.exe
pop3pack.exe
pop3trap.exe
scanmailoutlook.exe
smoutlookpack.exe
webtrapnt.exe
euqmonitor.exe
smex_activeupda
smex_master.exe
smex_remoteconf
smex_systemwatc
svcgenerichost
spntsvc.exe
stopp.exe
stwatchdog.exe
usbguard.exe
uploadrecord.exe
sbamsvc.exe
vrvmail.exe
vrvmon.exe
vrvnet.exe
vrv.exe
wrsa.exe
networkagent.exe
websensecontrolservice.exe
mpcmdrun.exe
msascui.exe
msmpeng.exe
mspmspsv.exe
kb891711.exe
zavaux.exe
zavcore.exe
zillya.exe
zlclient.exe
vsmon.exe
forcefield.exe
iswmgr.exe
zapro.exe
zonealarm.exe
mantispm.exe
Acronis VSS Provider
Enterprise Client Service
Sophos Agent
Sophos AutoUpdate Service
Sophos Clean Service
Sophos Device Control Service
Sophos File Scanner Service
Sophos Health Service
Sophos MCS Agent
Sophos MCS Client
Sophos Message Router
Sophos Safestore Service
Sophos System Protection Service
Sophos Web Control Service
SQLsafe Backup Service
SQLsafe Filter Service
Symantec System Recovery
Veeam Backup Catalog Data Service
AcronisAgent
AcrSch2Svc
Antivirus
ARSM
BackupExecAgentAccelerator
BackupExecAgentBrowser
BackupExecDeviceMediaService
BackupExecJobEngine
BackupExecManagementService
BackupExecRPCService
BackupExecVSSProvider
bedbg
DCAgent
EPSecurityService
EPUpdateService
EraserSvc11710
EsgShKernel
FA_Scheduler
IISAdmin
IMAP4Svc
macmnsvc
masvc
MBAMService
MBEndpointAgent
McAfeeEngineService
McAfeeFramework
McAfeeFrameworkMcAfeeFramework
McShield
McTaskManager
mfemms
mfevtp
mozyprobackup
MsDtsServer
MsDtsServer100
MsDtsServer110
MSExchangeES
MSExchangeIS
MSExchangeMGMT
MSExchangeMTA
MSExchangeSA
MSExchangeSRS
MSOLAP$SQL_2008
MSOLAP$SYSTEM_BGC
MSOLAP$TPS
MSOLAP$TPSAMA
MSSQL$BKUPEXEC
MSSQL$ECWDB2
MSSQL$PRACTICEMGT
MSSQL$PRACTTICEBGC
MSSQL$PROFXENGAGEMENT
MSSQL$SBSMONITORING
MSSQL$SHAREPOINT
MSSQL$SQL_2008
MSSQL$SYSTEM_BGC
MSSQL$TPS
MSSQL$TPSAMA
MSSQL$VEEAMSQL2008R2
MSSQL$VEEAMSQL2012
MSSQLFDLauncher
MSSQLFDLauncher$PROFXENGAGEMENT
MSSQLFDLauncher$SBSMONITORING
MSSQLFDLauncher$SHAREPOINT
MSSQLFDLauncher$SQL_2008
MSSQLFDLauncher$SYSTEM_BGC
MSSQLFDLauncher$TPS
MSSQLFDLauncher$TPSAMA
MSSQLSERVER
MSSQLServerADHelper100
MSSQLServerOLAPService
MySQL57
ntrtscan
OracleClientCache80
PDVFSService
POP3Svc
ReportServer
ReportServer$SQL_2008
ReportServer$SYSTEM_BGC
ReportServer$TPS
ReportServer$TPSAMA
RESvc
sacsvr
SamSs
SAVAdminService
SAVService
SDRSVC
SepMasterService
ShMonitor
Smcinst
SmcService
SMTPSvc
SNAC
SntpService
sophossps
SQLAgent$BKUPEXEC
SQLAgent$ECWDB2
SQLAgent$PRACTTICEBGC
SQLAgent$PRACTTICEMGT
SQLAgent$PROFXENGAGEMENT
SQLAgent$SBSMONITORING
SQLAgent$SHAREPOINT
SQLAgent$SQL_2008
SQLAgent$SYSTEM_BGC
SQLAgent$TPS
SQLAgent$TPSAMA
SQLAgent$VEEAMSQL2008R2
SQLAgent$VEEAMSQL2012
SQLBrowser
SQLSafeOLRService
SQLSERVERAGENT
SQLTELEMETRY
SQLTELEMETRY$ECWDB2
SQLWriter
SstpSvc
svcGenericHost
swi_filter
swi_service
swi_update_64
TmCCSF
tmlisten
TrueKey
TrueKeyScheduler
TrueKeyServiceHelper
UI0Detect
VeeamBackupSvc
VeeamBrokerSvc
VeeamCatalogSvc
VeeamCloudSvc
VeeamDeploymentService
VeeamDeploySvc
VeeamEnterpriseManagerSvc
VeeamMountSvc
VeeamNFSSvc
VeeamRESTSvc
VeeamTransportSvc
W3Svc
wbengine
WRSVC
VeeamHvIntegrationSvc
swi_update
SQLAgent$CXDB
SQLAgent$CITRIX_METAFRAME
SQL Backups
MSSQL$PROD
Zoolz 2 Service
MSSQLServerADHelper
SQLAgent$PROD
msftesql$PROD
NetMsmqActivator
EhttpSrv
ekrn
ESHASRV
MSSQL$SOPHOS
SQLAgent$SOPHOS
klnagent
MSSQL$SQLEXPRESS
SQLAgent$SQLEXPRESS
kavfsslp
KAVFSGT
KAVFS
mfefire
avast! Antivirus
aswBcc
Avast Business Console Client Antivirus Service
mfewc
Telemetryserver
WdNisSvc
WinDefend
MCAFEETOMCATSRV530
MCAFEEEVENTPARSERSRV
MSSQLFDLauncher$ITRIS
MSSQL$EPOSERVER
MSSQL$ITRIS
SQLAgent$EPOSERVER
SQLAgent$ITRIS
SQLTELEMETRY$ITRIS
MsDtsServer130
SSISTELEMETRY130
MSSQLLaunchpad$ITRIS
BITS
BrokerInfrastructure
epag
EPIntegrationService
EPProtectedService
epredline
TmPfw
SentinelAgent
SentinelHelperService
LogProcessorService
SentinelStaticEngine
DB2GOVERNOR_DB2COPY1
DB2LICD_DB2COPY1
DB2MGMTSVC_DB2COPY1
DB2REMOTECMD_DB2COPY1
DB2DAS00
DB2-0
DB2INST2
IBMDataServerMgr
IBMDSServer41
MSSQL$CITRIX_METAFRAME
RumorServer
myAgtSvc
McAfee SiteAdvisor Enterprise Service
Alerter
ERSvc
Eventlog
ImapiService
NetDDE
NtLmSsp
NtmsSvc
odserv
SnowInventoryClient
TlntSvr
VMTools
VMware
WebClient
WinVNC4
BlueStripeCollector
Cissesrv
CpqRcmc3
gupdate
gupdatem
HealthService
NimbusWatcherService
ProLiantMonitor
SDD_Service
sysdown
System
GoogleChromeElevationService
bcrservice
ccEvtMgr
ccSetMgr
CSAdmin
CSAuth
CSDbSync
CSLog
CSMon
CSRadius
CSTacacs
Symantec
VGAuthService
SepMasterServiceMig
vmware-converter-agent
vmware-converter-server
vmware-converter-worker
avbackup
MSSQL$NET2
Net2ClientSvc
NetSvc
SQLAgent$NET2
tpautoconnsvc
TPVCGateway
VMwareCAFCommAmqpListener
VMwareCAFManagementAgentHost
TPAutoConnSvc
AdobeARMservice
RSCDsvc
LRSDRVX
msvsmon90
IDriverT
MSMQ","Notes",0,1563489999,"","","","",""
"5d30f6f6-e1e8-453c-816b-390b68f8e8cf",1204,"Internal reference","text","Note:

If you are reading this text, it means, we've hacked your corporate network.
Now all your data is encrypted with very serious and powerful algorithms (AES256 and RSA-4,096).
These algorithms now in use in military intelligence, NSA and CIA .
No one can help you to restore your data without our special decipherer.
Don't even waste your time.
But there are good news for you.
We don't want to do any damage to your business.
We are working for profit.
The core of this criminal business is to give back your valuable data in the original form (for ransom of course).
In order to prove that we can restore all your data, we'll decrypt 3 of your files for free.
Please, attach 2-3 encrypted files to your first letter.
Each file must be less than 5 Mb, non-archived and your files should not contain valuable information
(databases, backups, large word files or excel sheets, etc.).
You will receive decrypted samples and our conditions how to get the decipherer.
For the fastest solution of the problem, please, write immediately in your first letter:
the name of your company,
the domain name of your corporate network and
the URL of your corporate website
It is important !
And please do not start your first letter to us with the words:
""It's a mistake !! Our company is just trimming and grooming little dogs. We don't have money at all.""
""There is a big mistake on our site !
We are not leaders in our industry and all our competitors don't suck our huge dick.
We're just 
 small company, and we are dying because of hard competition.""
""We are not the Super Mega International Corporation ltd., we are just a nursery etc.""
We see it 5 times a day. This shit doesn't work at all !!!
Don't waste our and your time.
Remember ! We don't work for food.

pwndb2am4tzkvold.onion

You have to pay for decryption in Bitcoins (BTC).
If you think you pay $500 and you'll get the decryptor, you are 50 million light years away from reality :)
The ransom begins from 2-3 BTC up to 600 BTC.
If you don't have money don't even write to us.
We don't do charity !
One more time :
1.(In first letter) write the name of your company, the domain name of your corporate network and the URL of your corporate website
2. Attach 2-3 encrypted files (we'll show you some magic)
3. Use Google in order to find out how to buy bitcoins fast
As soon as we get bitcoins you'll get all your decrypted data back.
Contact emails:
MckinnisKamariyah91@mail.com
ThomassenVallen1999@mail.com
Man is the master of everything and decides everything.","Note",0,1563490038,"","","","",""
"5d30f498-f628-440e-bb11-411668f8e8cf",1204,"Payload delivery","malware-sample","77ee63e36a52b5810d3a31e619ec2b8f5794450b563e95e4b446d5d3db4453b2|c12ab67f2835b3a867af6c91aa3d3039","",1,1563489432,"malware-sample","","5d30f498-88e8-4471-8483-411668f8e8cf","file","file"
"5d30f498-3328-412b-8529-411668f8e8cf",1204,"Payload delivery","filename","77ee63e36a52b5810d3a31e619ec2b8f5794450b563e95e4b446d5d3db4453b2","",0,1563489432,"filename","","5d30f498-88e8-4471-8483-411668f8e8cf","file","file"
"5d30f498-5148-47d4-9393-411668f8e8cf",1204,"Payload delivery","md5","c12ab67f2835b3a867af6c91aa3d3039","",1,1563489432,"md5","","5d30f498-88e8-4471-8483-411668f8e8cf","file","file"
"5d30f498-c89c-4913-b83b-411668f8e8cf",1204,"Payload delivery","sha1","9369e8f849fad6c87d630b08cc91a320ccafd367","",1,1563489432,"sha1","","5d30f498-88e8-4471-8483-411668f8e8cf","file","file"
"5d30f498-e24c-4fd6-aa3e-411668f8e8cf",1204,"Payload delivery","sha256","77ee63e36a52b5810d3a31e619ec2b8f5794450b563e95e4b446d5d3db4453b2","",1,1563489432,"sha256","","5d30f498-88e8-4471-8483-411668f8e8cf","file","file"
"5d30f498-e594-422f-814e-411668f8e8cf",1204,"Other","size-in-bytes",972288,"",0,1563489432,"size-in-bytes","","5d30f498-88e8-4471-8483-411668f8e8cf","file","file"
"5d30f4bc-3e9c-437f-8203-390b68f8e8cf",1204,"Payload delivery","malware-sample","10000000.dll|3a5da04669a4347b3f7a55c864f5a003","",1,1563489468,"malware-sample","","5d30f4bc-5284-463e-ab2f-390b68f8e8cf","file","file"
"5d30f4bc-af58-42fe-b3a6-390b68f8e8cf",1204,"Payload delivery","filename","10000000.dll","",0,1563489468,"filename","","5d30f4bc-5284-463e-ab2f-390b68f8e8cf","file","file"
"5d30f4bc-c670-45ec-843e-390b68f8e8cf",1204,"Payload delivery","md5","3a5da04669a4347b3f7a55c864f5a003","",1,1563489468,"md5","","5d30f4bc-5284-463e-ab2f-390b68f8e8cf","file","file"
"5d30f4bc-f5c0-4866-9224-390b68f8e8cf",1204,"Payload delivery","sha1","a019e0ff24d773592c42443d5e51473219e8b874","",1,1563489468,"sha1","","5d30f4bc-5284-463e-ab2f-390b68f8e8cf","file","file"
"5d30f4bc-50d0-4dd2-bbcf-390b68f8e8cf",1204,"Payload delivery","sha256","8b7aa0b20a97f3b19894b87a436ad94b80635a5e5336208f4dc59525ce9287d8","",1,1563489468,"sha256","","5d30f4bc-5284-463e-ab2f-390b68f8e8cf","file","file"
"5d30f4bc-0384-460a-9818-390b68f8e8cf",1204,"Other","size-in-bytes",743424,"",0,1563489468,"size-in-bytes","","5d30f4bc-5284-463e-ab2f-390b68f8e8cf","file","file"
MegaCortex Ransomware: 
MD5: c12ab67f2835b3a867af6c91aa3d3039

mbedtls_cipher_setup
ext: .megac0rtx

July 15 build

Exports:
ss2
start

Blacklisted Files & Folders:
.dll
.exe
.sys
.mui
.tmp
.lnk
.config
.manifest
.tlb
.olb
.blf
.ico
.regtrans-ms
.devicemetadata-ms
.settingcontent-ms
.bat
.cmd
.ps1
desktop.ini
iconcache.db
ntuser.dat
ntuser.ini
ntuser.dat.log1
ntuser.dat.log2
usrclass.dat
usrclass.dat.log1
usrclass.dat.log2
bootmgr
bootnxt
temp\
.+\\Microsoft\\(User Account Pictures|Windows\\(Explorer|Caches)|Device Stage\\Device|Windows)\\

Service & Process Kill (taskkill, net.exe & sc config " start=disabled):
ccflic0.exe
ccflic4.exe
healthservice.exe
ilicensesvc.exe
nimbus.exe
prlicensemgr.exe
certificateprovider.exe
proficypublisherservice.exe
proficysts.exe
erlsrv.exe
vmtoolsd.exe
managementagenthost.exe
vgauthservice.exe
epmd.exe
hasplmv.exe
spooler.exe
hdb.exe
ntservices.exe
n.exe
monitoringhost.exe
win32sysinfo.exe
inet_gethost.exe
taskhostw.exe
proficy administrator.exe
ntevl.exe
prproficymgr.exe
prrds.exe
prrouter.exe
prconfigmgr.exe
prgateway.exe
premailengine.exe
pralarmmgr.exe
prftpengine.exe
prcalculationmgr.exe
prprintserver.exe
prdatabasemgr.exe
preventmgr.exe
prreader.exe
prwriter.exe
prsummarymgr.exe
prstubber.exe
prschedulemgr.exe
cdm.exe
musnotificationux.exe
npmdagent.exe
client64.exe
keysvc.exe
server_eventlog.exe
proficyserver.exe
server_runtime.exe
config_api_service.exe
fnplicensingservice.exe
workflowresttest.exe
proficyclient.exe
vmacthlp.exe
msdtssrvr.exe
sqlservr.exe
msmdsrv.exe
reportingservicesservice.exe
dsmcsvc.exe
winvnc4.exe
client.exe
collwrap.exe
bluestripecollector.exe
sqlbrowser.exe
dsmcad.exe
nimcluster.exe
googleupdate.exe
smc.exe
bcrservice.exe
dbsrv9.exe
rtvscan.exe
bcreporter.exe
csadmin.exe
csdbsync.exe
csmon.exe
csauth.exe
cslog.exe
csradius.exe
cstacacs.exe
url_response.exe
vmware-converter-a.exe
vmware-converter.exe
avagent.exe
paxton.net2.clientservice.exe
paxton.net2.commsserverservice.exe
avscc.exe
prunsrv.exe
googlecrashhandler.exe
googlecrashhandler64.exe
vmwaretray.exe
nd2svc.exe
tnslsnr.exe
omtsreco.exe
oracle.exe
patrolagent.exe
scfagent_64.exe
patrolperf.exe
rscdsvc.exe
rscd.exe
pmgreader.exe
firefox.exe
chrome.exe
netsession_win.exe
pcsws.exe
pcscm.exe
cwbunnav.exe
rdrcef.exe
ndrvx.exe
ndrvs.exe
dr_serviceengine.exe
teamviewer_service.exe
sqlagent.exe
dwrcst.exe
ccm messaging.exe
zoolz.exe
agntsvc.exe
dbeng50.exe
dbsnmp.exe
encsvc.exe
excel.exe
firefoxconfig.exe
infopath.exe
isqlplussvc.exe
msaccess.exe
msftesql.exe
mspub.exe
mydesktopqos.exe
mydesktopservice.exe
mysqld.exe
mysqld-nt.exe
mysqld-opt.exe
ocautoupds.exe
ocomm.exe
ocssd.exe
onenote.exe
outlook.exe
powerpnt.exe
sqbcoreservice.exe
sqlwriter.exe
steam.exe
synctime.exe
tbirdconfig.exe
thebat.exe
thebat64.exe
thunderbird.exe
visio.exe
winword.exe
wordpad.exe
xfssvccon.exe
tmlisten.exe
pccntmon.exe
cntaosmgr.exe
ntrtscan.exe
mbamtray.exe
qhactivedefense.exe
qhwatchdog.exe
qhsafetray.exe
avgsvc.exe
avgui.exe
v3lite.exe
v3main.exe
v3sp.exe
avastui.exe
avastsvc.exe
avguard.exe
avshadow.exe
avgnt.exe
avira.servicehost.exe
avira.systray.exe
bdagent.exe
bdredline.exe
bdss.exe
bullguardbhvscanner.exe
bullguardscanner.exe
bullguardtray.exe
bullguardupdate.exe
bullguard.exe
cmdagent.exe
cistray.exe
cis.exe
spideragent.exe
dwengine.exe
dwarkdaemon.exe
dwnetfilter.exe
a2service.exe
a2guard.exe.a2start.exe
egui.exe
ekrn.exe
fshoster32.exe
fshoster64.exe
fortisslvpndaemon.exe
fortiesnac.exe
fortiwf.exe
fortitray.exe
fchelper64.exe
fortiproxy.exe
fcappdb.exe
fcdblog.exe
avp.exe
avpui.exe
mbamservice.exe
mcsacore.exe
mcapexe.exe
mcshield.exe
mcsvhost.exe
nortonsecurity.exe
psuaservice.exe
psuamain.exe
psanhost.exe
sdrservice.exe
swc_service.exe
swi_service.exe
ssp.exe
ccsvchst.exe
smcgui.exe
coreserviceshell.exe
coreframeworkhost.exe
uiwatchdog.exe
uiseagnt.exe
paamsrv.exe
psh_svc.exe
aupdrun.exe
acaas.exe
acaegmgr.exe
acaif.exe
acais.exe
ahnsd.exe
ahnsdsv.exe
autoup.exe
v3clnsrv.exe
v3medic.exe
v3svc.exe
aflogvw.exe
ahnrpt.exe
atwsctsk.exe
v3exec.exe
v3imscn.exe
monsvcnt.exe
monsysnt.exe
aexnsrcvsvc.exe
aexsvc.exe
atrshost.exe
ctdataload.exe
aexagentuihost.exe
aexnsagent.exe
aclntusr.exe
aexswdusr.exe
pxemtftp.exe
aclient.exe
securitycenter.exe
starta.exe
stopa.exe
anvir.exe
csrss_tc.exe
ashavast.exe
ashbug.exe
ashchest.exe
ashcmd.exe
ashdisp.exe
ashenhcd.exe
ashlogv.exe
ashmaisv.exe
ashpopwz.exe
ashquick.exe
ashserv.exe
ashsimp2.exe
ashsimpl.exe
ashskpcc.exe
ashskpck.exe
ashupd.exe
ashwebsv.exe
aswdisp.exe
aswregsvr.exe
aswserv.exe
aswupdsv.exe
aswwebsv.exe
avengine.exe
afwserv.exe
avastemupdate.exe
unsecapp.exe
avgamsvr.exe
avgas.exe
avgcc32.exe
avgcc.exe
avgctrl.exe
avgdiag.exe
avgemc.exe
avgfws8.exe
avgfwsrv.exe
avginet.exe
avgmsvr.exe
avgrssvc.exe
avgscanx.exe
avgserv9.exe
avgserv.exe
avgupd.exe
avgupdln.exe
avgupsvc.exe
avgvv.exe
avgwb.dat
avgw.exe
avgwizfw.exe
guard.exe
avgcsrvx.exe
avgidsagent.exe
avgidsmonitor.exe
avgidsui.exe
avgidswatcher.exe
avgam.exe
avgnsx.exe
avgfws9.exe
avgrsx.exe
avgtray.exe
avgwdsvc.exe
sidebar.exe
avgchsvx.exe
avgcmgr.exe
avgemcx.exe
avgfws.exe
avgmfapx.exe
avgcefrend.exe
avgcsrva.exe
avgemca.exe
avgnsa.exe
avgrsa.exe
loggingserver.exe
toolbarupdater.exe
wtusystemsuport.exe
avgregcl.exe
avgsystx.exe
vprot.exe
avcenter.exe
avconfig.exe
avesvc.exe
avmailc.exe
avmcdlg.exe
avnotify.exe
avscan.exe
guardgui.exe
avadmin.exe
avfwsvc.exe
avwebgrd.exe
fwinst.exe
sysoptenginesvc.exe
bavtray.exe
bhipssvc.exe
bmrt.exe
seccenter.exe
gziface.exe
gzserv.exe
bdc.exe
bdlite.exe
bdmcon.exe
bdsubmit.exe
deloeminfs.exe
livesrv.exe
setloadorder.exe
vsserv.exe
xcommsvr.exe
bka.exe
bkavsystemserver.exe
blupro.exe
blackd.exe
blackice.exe
proutil.exe
rapapp.exe
basfipm.exe
isafe.exe
cavrid.exe
vetmsg.exe
amswmagt
caf.exe
capmuam
agt.exe
ccnfagent.exe
ccsmagtd.exe
cfftplugin.exe
cfnotsrvd.exe
cfsmsmd.exe
alert.exe
igateway.exe
inotask.exe
caantispyware.exe
caavcmdscan.exe
caav.exe
caavguiscan.exe
cafw.exe
calogdump.exe
capfaem.exe
capfsem.exe
cappactiveprotection.exe
casecuritycenter.exe
caunst.exe
cavrep.exe
cctray.exe
ccupdate.exe
isafinst.exe
itmrt_supportdiagnostics.exe
itmrtsvc.exe
itmrt_trace.exe
ppclean.exe
umxagent.exe
umxcfg.exe
umxfwhlp.exe
umxpol.exe
unvet32.exe
capfasem.exe
ccprovsp.exe
ppctlpriv.exe
casc.exe
ccschedulersvc.exe
ccsystemreport.exe
inonmsrv.exe
inoweb.exe
auth8021x.exe
krbcc32s.exe
pep.exe
realmon.exe
repmgr64.exe
csacontrol.exe
leventmgr.exe
okclient.exe
clamscan.exe
clamtray.exe
clamwin.exe
ccemflsv.exe
cssauth.exe
cavscan.exe
clps.exe
clpsla.exe
clpsls.exe
cmdinstall.exe
cfpconfig.exe
cfp.exe
cfplogvw.exe
cfpsbmit.exe
cfpupdat.exe
crashrep.exe
cpf.exe
cfpconfg.exe
csfalconservice.exe
cylanceui.exe
cylancesvc.exe
cramtray.exe
crssvc.exe
amsvc.exe
frzstate2k.exe
drwagnui.exe
drweb32.exe
drweb32w.exe
drweb386.exe
drwebcgp.exe
drwebdc.exe
drweb.exe
drwebmng.exe
drwebscd.exe
drwebupw.exe
drwebwcl.exe
drwebwin.exe
drwinst.exe
spiderml.exe
spidernt.exe
spiderui.exe
drwagntd.exe
drwupgrade.exe
drwebcom.exe
eeyeevnt.exe
retinaengine.exe
a2guard.exe
a2start.exe
administrator.exe
control_panel.exe
usergate.exe
esmagent.exe
era.exe
ppmcativedetection.exe
vettray.exe
cavtray.exe
inorpc.exe
inort.exe
ca.exe
caissdt.exe
etagent.exe
etloganalyzer.exe
etrssfeeds.exe
evtarmgr.exe
evtmgr.exe
etreporter.exe
etconsole3.exe
etwcontrolpanel.exe
useranalysis.exe
etcorrel.exe
evtprocessecfile.exe
etscheduler.exe
useractivity.exe
traptrackermgr.exe
ewidoctrl.exe
ewidoguard.exe
nslocollectorservice.exe
fmon.exe
fortifw.exe
update_task.exe
fpavserver.exe
fprottray.exe
fameh32.exe
fspex.exe
fsaa.exe
bwgo0000
fch32.exe
fih32.exe
fsaua.exe
fsav32.exe
fscuif.exe
fsdfwd.exe
fsgk32.exe
fsgk32st.exe
fsguidll.exe
fsguiexe.exe
fshdll32.exe
fsm32.exe
fsma32.exe
fsmb32.exe
fsorsp.exe
fspc.exe
fsqh.exe
fssm32.exe
setupguimngr.exe
tnbutil.exe
fsavgui.exe
gdscan.exe
avkproxy.exe
avkservice.exe
avktray.exe
avkwctl.exe
gdfirewalltray.exe
gdfwsvc.exe
endpointsecurity.exe
esecservice.exe
gfireporterservice.exe
esecagntservice.exe
rcsvcmon.exe
dolphincharge.e
dolphincharge.exe
loggetor.exe
netalertclient.exe
printdevice.exe
pwdfilthelp.exe
pthosttr.exe
hpqwmiex.exe
ntcaagent.exe
ntcadaemon.exe
ntcaservice.exe
privacyiconclient.exe
rapuisvc.exe
vpatch.exe
tclproc.exe
isscsf.exe
issdaemon.exe
kvdetech.exe
kvmonxp_2.kxp
kvmonxp.kxp
kvolself.exe
kvsrvxp_1.exe
kvsrvxp.exe
kvxp.kxp
ppppwallrun.exe
avpcc.exe
avpexec.exe
avpm.exe
avpncc.exe
avps.exe
avpupd.exe
kav.exe
kavisarv.exe
kavmm.exe
kavss.exe
kavsvc.exe
kis.exe
klnagent.exe
klswd.exe
klwtblfs.exe
kwsprod.exe
up2date.exe
klserver.exe
oespamtest.exe
kavadapterexe.exe
kavlotsingleton.exe
kavfsgt.exe
kavfsrcn.exe
kavfs.exe
kavfswp.exe
kavshell.exe
klnacserver.exe
avpdtagt.exe
netcfg.exe
kavfsscs.exe
kavtray.exe
persfw.exe
avserver.exe
winroute.exe
wrctrl.exe
kabackreport.exe
kaccore.exe
kanmcmain.exe
kastray.exe
kislive.exe
kmailmon.exe
knupdatemain.exe
kswebshield.exe
kxeserv.exe
uplive.exe
kansgui.exe
kansvr.exe
kavstart.exe
kpfwsvc.exe
kwatch.exe
kav32.exe
kissvc.exe
kpfw32.exe
system.exe
wssfcmai.exe
aawservice.exe
ad-aware2007.exe
nlsvc.exe
engineserver.exe
eventparser.exe
log_qtine.exe
mfeann.exe
nailgpip.exe
rpcserv.exe
srvmon.exe
mcagent.exe
mfemactl.exe
macmnsvc.exe
masvc.exe
masalert.exe
msssrv.exe
massrv.exe
msscli.exe
mcshld9x.exe
mgavrtcl.exe
mcappins.exe
mfecanary.exe
macompatsvc.exe
mcvsrte.exe
mfefire.exe
dao_log.exe
firesvc.exe
firetray.exe
mfeesp.exe
naprdmgr.exe
cpd.exe
mfefw.exe
frameworkservic
cmgrdian.exe
mcshell.exe
mfehcs.exe
mcinfo.exe
hwapi.exe
mcafeedatabackup.exe
mcmscsvc.exe
mcnasvc.exe
mcods.exe
mcpromgr.exe
mcproxy.exe
mcuimgr.exe
mpfsrv.exe
mpsevh.exe
mps.exe
msksrver.exe
redirsvc.exe
saservice.exe
siteadv.exe
mfemms.exe
neotrace.exe
vshwin32.exe
mpfagent.exe
mpfconsole.exe
mpf.exe
mpfservice.exe
mpftray.exe
mscifapp.exe
mfevtps.exe
qclean.exe
mcregwiz.exe
rssensor.exe
safeservice.exe
ncdaemon.exe
mcdash.exe
mcdetect.exe
ssscheduler.exe
sahookmain.exe
mskdetct.exe
msksrvr.exe
mskagent.exe
stinger.exe
mcsysmon.exe
mctskshd.exe
mfetp.exe
myagttry.exe
mcupdmgr.exe
rulaunch.exe
mcvsshld.exe
tbmon.exe
alogserv.exe
mcmnhdlr.exe
mghtml.exe
edisk.exe
scan32.exe
frameworkservice.exe
mcconsol.exe
mcscript_inuse.exe
mctray.exe
mcupdate.exe
shstat.exe
udaterui.exe
updaterui.exe
mcepoc.exe
mcepocfg.exe
mcpalmcfg.exe
mcwcecfg.exe
mcwce.exe
frameworkservic.exe
vsmain.exe
oasclnt.exe
vsstat.exe
mcvsftsn.exe
avconsol.exe
avsynmgr.exe
vstskmgr.exe
webscanx.exe
mfewc.exe
mfewch.exe
giantantispywaremain.exe
giantantispywareupdater.exe
gcasservalert.exe
gcascleaner.exe
gcasinstallhelper.exe
gcasnotice.exe
gcasdtserv.exe
gcasserv.exe
gcasswupdater.exe
fcsms.exe
fcssas.exe
nissrv.exe
dpmra.exe
msseces.exe
wscntfy.exe
securitymanager.exe
aesecurityservice.exe
deteqt.agent.exe
omniagent.exe
nerosvc.exe
seanalyzertool.exe
spyemergency.exe
spyemergencysrv.exe
nlclient.exe
crdm.exe
nmagent.exe
ehttpsrv.exe
nod32.exe
nod32krn.exe
nod32kui.exe
nod32view.exe
cclaw.exe
elogsvc.exe
nip.exe
nipsvc.exe
njeeves.exe
npfmsg2.exe
npfmsg.exe
npfsvice.exe
nrmenctb.exe
nvcoas.exe
nvcsched.exe
nymse.exe
zanda.exe
zlh.exe
ixaptsvc.exe
ixavsvc.exe
ixfwsvc.exe
emlproui.exe
emlproxy.exe
mpsvc.exe
onlinent.exe
onlnsvc.exe
scanmsg.exe
scanwscs.exe
tsansrf.exe
tsatisy.exe
tscutynt.exe
tsmpnt.exe
upschd.exe
xfilter.exe
aps.exe
aus.exe
outpost.exe
adminserver.exe
avtask.exe
clshield.exe
console.exe
cpntsrv.exe
padfsvr.exe
pasystemtray.exe
pavfnsvr.exe
pavkre.exe
pavprot.exe
pavreport.exe
pnmsrv.exe
psimsvc.exe
pavupg.exe
remupd.exe
iface.exe
pavfires.exe
pavmail.exe
pavprsrv.exe
pavsched.exe
pavsrv50.exe
pavsrv51.exe
pavsrv52.exe
prevsrv.exe
tpsrv.exe
pagent.exe
pagentwd.exe
psctris.exe
apvxdwin.exe
inicio.exe
pavbckpt.exe
pavjobs.exe
psctrls.exe
pshost.exe
psimreal.exe
pskmssvc.exe
srvload.exe
webproxy.exe
avltmain.exe
firewallgui.exe
pviewer.exe
pview.exe
pmon.exe
qoeloader.exe
fws.exe
ccenter.exe
ravxp.exe
rfwproxy.exe
rfwstub.exe
knownsvr.exe
ras.exe
rasupd.exe
upfile.exe
rstray.exe
ravalert.exe
rav.exe
ravmond.exe
ravmon.exe
ravservice.exe
ravstub.exe
ravtask.exe
ravtray.exe
ravupdate.exe
rnreport.exe
rsnetsvr.exe
scanfrm.exe
rfwmain.exe
rfwsrv.exe
winlog.exe
omslogmanager.exe
snhwsrv.exe
snicheckadm.exe
snichecksrv.exe
snicon.exe
snsrv.exe
smsx.exe
svcharge.exe
svdealer.exe
svframe.exe
svtray.exe
sschk.exe
trjscan.exe
trupd.exe
ssecuritymanager.exe
dltray.exe
dlservice.exe
almon.exe
lmon.exe
savadminservice.exe
savservice.exe
sweepsrv.sys
swnetsup.exe
alsvc.exe
alupdate.exe
savmain.exe
sav32cli.exe
certificationmanagerservicent.exe
emlibupdateagentnt.exe
managementagentnt.exe
mgntsvc.exe
routernt.exe
schdsrvc.exe
scfmanager.exe
scfservice.exe
scftray.exe
op_viewer.exe
sgbhp.exe
pctsauxs.exe
pctsgui.exe
pctssvc.exe
pctstray.exe
regmech.exe
sdtrayapp.exe
svcntaux.exe
swdsvc.exe
swnxt.exe
execstat.exe
seestat.exe
swserver.exe
slee81.exe
kpf4gui.exe
kpf4ss.exe
wrspysetup.exe
acctmgr.exe
alertsvc.exe
alunotify.exe
aluschedulersvc.exe
appsvc32.exe
ccap.exe
ccapp.exe
ccevtmgr.exe
ccproxy.exe
ccpxysvc.exe
ccsetmgr.exe
checkup.exe
cka.exe
comhost.exe
cpdclnt.exe
csinject.exe
csinsm32.exe
csinsmnt.exe
dbserv.exe
defwatch.exe
defwatch
diskmon.exe
djsnetcn.exe
doscan.exe
dwhwizrd.exe
fwcfg.exe
ghost_2.exe
ghosttray.exe
icepack.exe
idsinst.exe
ispwdsvc.exe
issvc.exe
isuac.exe
luall.exe
lucallbackproxy.exe
lucoms~1.exe
lucoms.exe
mcui32.exe
navapsvc.exe
navapw32.exe
navectrl.exe
navelog.exe
navesp.exe
navshcom.exe
navw32.exe
navwnt.exe
ndetect.exe
ngctw32.exe
ngserver.exe
nisoptui.exe
nisserv.exe
nisum.exe
nmain.exe
npfmntor.exe
nprotect.exe
npscheck.exe
npssvc.exe
nscsrvce.exe
nsctop.exe
nsmdtr.exe
olfsnt40.exe
opscan.exe
poproxy.exe
pqibrowser.exe
pqv2isvc.exe
pxeservice.exe
qdcsfs.exe
qserver.exe
reportersvc.exe
rnav.exe
savfmsesp.exe
savroam.exe
savscan.exe
savui.exe
sbserv.exe
scan
explicit.exe
semsvc.exe
sesclu.exe
sevinst.exe
smsectrl.exe
smselog.exe
smsesjm.exe
smsesp.exe
smsesrv.exe
smsetask.exe
smseui.exe
sms.exe
sndmon.exe
sndsrvc.exe
spbbcsvc.exe
symlcsvc.exe
symproxysvc.exe
symsport.exe
symtray.exe
symwsc.exe
sysdoc32.exe
ucservice.exe
updtnv28.exe
urllstck.exe
usrprmpt.exe
v2iconsole.exe
vpc32.exe
vpdn_lu.exe
vprosvc.exe
wfxctl32.exe
wfxmod32.exe
wfxsnt40.exe
lucomserver.exe
savfmselog.exe
savfmsesjm.exe
savfmsectrl.exe
savfmsespamstatsmanager.exe
savfmsesrv.exe
savfmsetask.exe
savfmseui.exe
snac.exe
ssm.exe
reportsvc.exe
vptray.exe
procexp.exe
tdimon.exe
tfun.exe
tfgui.exe
tfservice.exe
tftray.exe
tiaspn~1.exe
traflnsp.exe
asupport.exe
isntsmtp.exe
nsmdemf.exe
nsmdmon.exe
nsmdreal.exe
nsmdsch.exe
ofcdog.exe
pccnt.exe
pccntupd.exe
pcctlcom.exe
pcscnsrv.exe
schupd.exe
tmntsrv.exe
tmpfw.exe
tmproxy.exe
tmas.exe
entitymain.exe
aphost.exe
lwdmserver.exe
mrf.exe
isntsysmonitor
ofcpfwsvc.exe
dwwin.exe
patch.exe
pccclient.exe
pccguide.exe
pcclient.exe
pccpfw.exe
pcscan.exe
pntiomon.exe
pop3pack.exe
pop3trap.exe
scanmailoutlook.exe
smoutlookpack.exe
webtrapnt.exe
euqmonitor.exe
smex_activeupda
smex_master.exe
smex_remoteconf
smex_systemwatc
svcgenerichost
spntsvc.exe
stopp.exe
stwatchdog.exe
usbguard.exe
uploadrecord.exe
sbamsvc.exe
vrvmail.exe
vrvmon.exe
vrvnet.exe
vrv.exe
wrsa.exe
networkagent.exe
websensecontrolservice.exe
mpcmdrun.exe
msascui.exe
msmpeng.exe
mspmspsv.exe
kb891711.exe
zavaux.exe
zavcore.exe
zillya.exe
zlclient.exe
vsmon.exe
forcefield.exe
iswmgr.exe
zapro.exe
zonealarm.exe
mantispm.exe
Acronis VSS Provider
Enterprise Client Service
Sophos Agent
Sophos AutoUpdate Service
Sophos Clean Service
Sophos Device Control Service
Sophos File Scanner Service
Sophos Health Service
Sophos MCS Agent
Sophos MCS Client
Sophos Message Router
Sophos Safestore Service
Sophos System Protection Service
Sophos Web Control Service
SQLsafe Backup Service
SQLsafe Filter Service
Symantec System Recovery
Veeam Backup Catalog Data Service
AcronisAgent
AcrSch2Svc
Antivirus
ARSM
BackupExecAgentAccelerator
BackupExecAgentBrowser
BackupExecDeviceMediaService
BackupExecJobEngine
BackupExecManagementService
BackupExecRPCService
BackupExecVSSProvider
bedbg
DCAgent
EPSecurityService
EPUpdateService
EraserSvc11710
EsgShKernel
FA_Scheduler
IISAdmin
IMAP4Svc
macmnsvc
masvc
MBAMService
MBEndpointAgent
McAfeeEngineService
McAfeeFramework
McAfeeFrameworkMcAfeeFramework
McShield
McTaskManager
mfemms
mfevtp
mozyprobackup
MsDtsServer
MsDtsServer100
MsDtsServer110
MSExchangeES
MSExchangeIS
MSExchangeMGMT
MSExchangeMTA
MSExchangeSA
MSExchangeSRS
MSOLAP$SQL_2008
MSOLAP$SYSTEM_BGC
MSOLAP$TPS
MSOLAP$TPSAMA
MSSQL$BKUPEXEC
MSSQL$ECWDB2
MSSQL$PRACTICEMGT
MSSQL$PRACTTICEBGC
MSSQL$PROFXENGAGEMENT
MSSQL$SBSMONITORING
MSSQL$SHAREPOINT
MSSQL$SQL_2008
MSSQL$SYSTEM_BGC
MSSQL$TPS
MSSQL$TPSAMA
MSSQL$VEEAMSQL2008R2
MSSQL$VEEAMSQL2012
MSSQLFDLauncher
MSSQLFDLauncher$PROFXENGAGEMENT
MSSQLFDLauncher$SBSMONITORING
MSSQLFDLauncher$SHAREPOINT
MSSQLFDLauncher$SQL_2008
MSSQLFDLauncher$SYSTEM_BGC
MSSQLFDLauncher$TPS
MSSQLFDLauncher$TPSAMA
MSSQLSERVER
MSSQLServerADHelper100
MSSQLServerOLAPService
MySQL57
ntrtscan
OracleClientCache80
PDVFSService
POP3Svc
ReportServer
ReportServer$SQL_2008
ReportServer$SYSTEM_BGC
ReportServer$TPS
ReportServer$TPSAMA
RESvc
sacsvr
SamSs
SAVAdminService
SAVService
SDRSVC
SepMasterService
ShMonitor
Smcinst
SmcService
SMTPSvc
SNAC
SntpService
sophossps
SQLAgent$BKUPEXEC
SQLAgent$ECWDB2
SQLAgent$PRACTTICEBGC
SQLAgent$PRACTTICEMGT
SQLAgent$PROFXENGAGEMENT
SQLAgent$SBSMONITORING
SQLAgent$SHAREPOINT
SQLAgent$SQL_2008
SQLAgent$SYSTEM_BGC
SQLAgent$TPS
SQLAgent$TPSAMA
SQLAgent$VEEAMSQL2008R2
SQLAgent$VEEAMSQL2012
SQLBrowser
SQLSafeOLRService
SQLSERVERAGENT
SQLTELEMETRY
SQLTELEMETRY$ECWDB2
SQLWriter
SstpSvc
svcGenericHost
swi_filter
swi_service
swi_update_64
TmCCSF
tmlisten
TrueKey
TrueKeyScheduler
TrueKeyServiceHelper
UI0Detect
VeeamBackupSvc
VeeamBrokerSvc
VeeamCatalogSvc
VeeamCloudSvc
VeeamDeploymentService
VeeamDeploySvc
VeeamEnterpriseManagerSvc
VeeamMountSvc
VeeamNFSSvc
VeeamRESTSvc
VeeamTransportSvc
W3Svc
wbengine
WRSVC
VeeamHvIntegrationSvc
swi_update
SQLAgent$CXDB
SQLAgent$CITRIX_METAFRAME
SQL Backups
MSSQL$PROD
Zoolz 2 Service
MSSQLServerADHelper
SQLAgent$PROD
msftesql$PROD
NetMsmqActivator
EhttpSrv
ekrn
ESHASRV
MSSQL$SOPHOS
SQLAgent$SOPHOS
klnagent
MSSQL$SQLEXPRESS
SQLAgent$SQLEXPRESS
kavfsslp
KAVFSGT
KAVFS
mfefire
avast! Antivirus
aswBcc
Avast Business Console Client Antivirus Service
mfewc
Telemetryserver
WdNisSvc
WinDefend
MCAFEETOMCATSRV530
MCAFEEEVENTPARSERSRV
MSSQLFDLauncher$ITRIS
MSSQL$EPOSERVER
MSSQL$ITRIS
SQLAgent$EPOSERVER
SQLAgent$ITRIS
SQLTELEMETRY$ITRIS
MsDtsServer130
SSISTELEMETRY130
MSSQLLaunchpad$ITRIS
BITS
BrokerInfrastructure
epag
EPIntegrationService
EPProtectedService
epredline
TmPfw
SentinelAgent
SentinelHelperService
LogProcessorService
SentinelStaticEngine
DB2GOVERNOR_DB2COPY1
DB2LICD_DB2COPY1
DB2MGMTSVC_DB2COPY1
DB2REMOTECMD_DB2COPY1
DB2DAS00
DB2-0
DB2INST2
IBMDataServerMgr
IBMDSServer41
MSSQL$CITRIX_METAFRAME
RumorServer
myAgtSvc
McAfee SiteAdvisor Enterprise Service
Alerter
ERSvc
Eventlog
ImapiService
NetDDE
NtLmSsp
NtmsSvc
odserv
SnowInventoryClient
TlntSvr
VMTools
VMware
WebClient
WinVNC4
BlueStripeCollector
Cissesrv
CpqRcmc3
gupdate
gupdatem
HealthService
NimbusWatcherService
ProLiantMonitor
SDD_Service
sysdown
System
GoogleChromeElevationService
bcrservice
ccEvtMgr
ccSetMgr
CSAdmin
CSAuth
CSDbSync
CSLog
CSMon
CSRadius
CSTacacs
Symantec
VGAuthService
SepMasterServiceMig
vmware-converter-agent
vmware-converter-server
vmware-converter-worker
avbackup
MSSQL$NET2
Net2ClientSvc
NetSvc
SQLAgent$NET2
tpautoconnsvc
TPVCGateway
VMwareCAFCommAmqpListener
VMwareCAFManagementAgentHost
TPAutoConnSvc
AdobeARMservice
RSCDsvc
LRSDRVX
msvsmon90
IDriverT
MSMQ 

Internal name:
payload.dll

elevate:
MEGA-G8=
x5gj5_gmG8.log

vssadmin delete shadows /all /for=
\vssadmin.exe
cipher /W: 
\cipher.exe
processed:
available VM: 
x5gj5_gmG8
 failed.
 KiB
 KiB/s 
start
KiB 
scaning 
 processed:

Note:

If you are reading this text, it means, we've hacked your corporate network.
Now all your data is encrypted with very serious and powerful algorithms (AES256 and RSA-4,096).
These algorithms now in use in military intelligence, NSA and CIA .
No one can help you to restore your data without our special decipherer.
Don't even waste your time.
But there are good news for you.
We don't want to do any damage to your business.
We are working for profit.
The core of this criminal business is to give back your valuable data in the original form (for ransom of course).
In order to prove that we can restore all your data, we'll decrypt 3 of your files for free.
Please, attach 2-3 encrypted files to your first letter.
Each file must be less than 5 Mb, non-archived and your files should not contain valuable information
(databases, backups, large word files or excel sheets, etc.).
You will receive decrypted samples and our conditions how to get the decipherer.
For the fastest solution of the problem, please, write immediately in your first letter:
the name of your company,
the domain name of your corporate network and
the URL of your corporate website
It is important !
And please do not start your first letter to us with the words:
"It's a mistake !! Our company is just trimming and grooming little dogs. We don't have money at all."
"There is a big mistake on our site !
We are not leaders in our industry and all our competitors don't suck our huge dick.
We're just 
 small company, and we are dying because of hard competition."
"We are not the Super Mega International Corporation ltd., we are just a nursery etc."
We see it 5 times a day. This shit doesn't work at all !!!
Don't waste our and your time.
Remember ! We don't work for food.
You have to pay for decryption in Bitcoins (BTC).
If you think you pay $500 and you'll get the decryptor, you are 50 million light years away from reality :)
The ransom begins from 2-3 BTC up to 600 BTC.
If you don't have money don't even write to us.
We don't do charity !
One more time :
1.(In first letter) write the name of your company, the domain name of your corporate network and the URL of your corporate website
2. Attach 2-3 encrypted files (we'll show you some magic)
3. Use Google in order to find out how to buy bitcoins fast
As soon as we get bitcoins you'll get all your decrypted data back.
Contact emails:
MckinnisKamariyah91@mail.com
ThomassenVallen1999@mail.com
Man is the master of everything and decides everything.
"""

s = restalker.reStalker(all=True)
# s = restalker.reStalker(tor=True)

for p in s.parse(target):
    print(p)
