# ruff: noqa: I001
# Import order: restalker must come before link_extractors to avoid circular import
from .restalker import (
    I2P_URL,
    IPFS_URL,
    MD5,
    PGP,
    SHA1,
    SHA256,
    Base64,
    Bitname_URL,
    BNB_Wallet,
    BTC_Wallet,
    Card_Number,
    DASH_Wallet,
    Discord_URL,
    DOT_Wallet,
    Email,
    ETH_Wallet,
    Freenet_URL,
    GA_Tracking_Code,
    Item,
    Keyphrase,
    Keyword,
    Location,
    Organization,
    OwnName,
    Password,
    Paste,
    Phone,
    Session_ID,
    Skype_URL,
    Telegram_URL,
    Tor_URL,
    Tox_ID,
    TW_Account,
    Username,
    Whatsapp_URL,
    XMR_Wallet,
    XRP_Wallet,
    ZEC_Wallet,
    Zeronet_URL,
    reStalker,
)
from . import link_extractors as link_extractors

# GLiNER model is loaded automatically when needed by TextAnalysis class
# No need for explicit model loading function

__version__ = "2.2.0"

# Explicitly define the public API
__all__ = [
    'reStalker',
    'Item',
    'Phone',
    'Email',
    'Keyphrase',
    'Keyword',
    'BTC_Wallet',
    'ETH_Wallet',
    'XMR_Wallet',
    'ZEC_Wallet',
    'DASH_Wallet',
    'DOT_Wallet',
    'XRP_Wallet',
    'BNB_Wallet',
    'TW_Account',
    'Tor_URL',
    'I2P_URL',
    'Freenet_URL',
    'Zeronet_URL',
    'Bitname_URL',
    'IPFS_URL',
    'Username',
    'Password',
    'Base64',
    'OwnName',
    'Telegram_URL',
    'Whatsapp_URL',
    'Skype_URL',
    'Discord_URL',
    'Paste',
    'MD5',
    'SHA1',
    'SHA256',
    'Organization',
    'Location',
    'PGP',
    'GA_Tracking_Code',
    'Card_Number',
    'Session_ID',
    'Tox_ID',
    'link_extractors',
]
